name: Rubocop

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  rubocop:
    name: rubocop
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Cache Gemfile.lock
        uses: actions/cache@v2
        with:
          path: ./vendor/bundle
          key: ${{ runner.os }}-rails-bundle-v1-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-rails-bundle-v1-

      - name: Ruby 2.7.4のセットアップ
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.4

      - name: pg gem の依存関係のインストール
        run: |
          sudo apt-get update; sudo apt-get install libpq-dev

      - name: gem install
        run: |
          gem install bundler -v 2.1.4
      - name: bundler install
        run: |
          bundle check || bundle install --path vendor/bundle --jobs 4 --retry 3
          
      - name: rubocopを実行実行
        run: |
          bundle exec rubocop --extra-details --display-style-guide --parallel --display-cop-names
